pipeline {
    agent any

    tools {
        python 'Python 3'
    }

    environment {
        VENV = 'venv'
    }

    stages {
        stage('Clone repository') {
            steps {
                git branch: 'main',
                    credentialsId: 'your-github-creds-id',
                    url: 'https://github.com/homemix/alx-backend-python.git'
            }
        }

        stage('Set up environment') {
            steps {
                sh '''
                    python3 -m venv $VENV
                    . $VENV/bin/activate
                    pip3 install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                    . $VENV/bin/activate
                    pytest messaging_app/tests --junitxml=report.xml
                '''
            }
        }

        stage('Publish test report') {
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }
}
