pipeline {
    agent any

    environment {
        VENV = 'venv'
        IMAGE_NAME = 'homemix/messaging-app:latest'
        DOCKER_CREDENTIALS_ID = 'dockerhub-credentials'
    }

    tools {
        python 'Python 3'
    }

    stages {
        stage('Clone repository') {
            steps {
                git branch: 'main',
                    credentialsId: 'your-github-creds-id',
                    url: 'https://github.com/homemix/alx-backend-python.git'
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                    python3 -m venv $VENV
                    . $VENV/bin/activate
                    pip3 install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                    . $VENV/bin/activate
                    pytest messaging_app/tests --junitxml=report.xml
                '''
            }
        }

        stage('Publish test report') {
            post {
                always {
                    junit 'report.xml'
                }
            }
        }

        stage('Build Docker image') {
            steps {
                sh 'docker build -t $IMAGE_NAME -f messaging_app/Dockerfile .'
            }
        }

        stage('Push Docker image') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIALS_ID}", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push $IMAGE_NAME
                    '''
                }
            }
        }
    }
}
